// Copyright Cartesi and individual authors (see AUTHORS)
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import "forge-std/console.sol";
import "forge-std/Test.sol";

import "./UArchInterpret.sol";
import "src/EmulatorConstants.sol";

pragma solidity ^0.8.30;

library ExternalUArchInterpret {
    function interpret(AccessLogs.Context memory accessLogs)
        external
        pure
        returns (UArchStep.UArchStepStatus)
    {
        return UArchInterpret.interpret(accessLogs);
    }
}

contract UArchInterpretTest is Test {
    using Memory for uint64;
    using AccessLogs for AccessLogs.Context;

    struct Entry {
        string binaryFilename;
        string finalRootHash;
        string initialRootHash;
        string logFilename;
        uint256 steps;
    }

    uint8 constant TEST_STATUS_X = 1;
    // test result code
    bytes8 constant TEST_SUCCEEDED = 0x00000000be1e7aaa; // Indicates that test has passed
    bytes8 constant TEST_FAILED = 0x00000000deadbeef; // Indicates that test has failed
    string constant CATALOG_PATH = "catalog.json";
    string constant JSON_PATH = "./test/uarch-log/";
    string constant BINARIES_PATH = "./test/uarch-bin/";
    string constant ENTRY_TYPE_DESCRIPTION =
        "Entry(string binaryFilename,string finalRootHash,string initialRootHash,string logFilename,uint256 steps)";

    function testBinaries() public view {
        Entry[] memory catalog =
            loadCatalog(string.concat(JSON_PATH, CATALOG_PATH));

        for (uint256 i = 0; i < catalog.length; i++) {
            if (bytes(catalog[i].binaryFilename).length == 0) {
                // Skip entries with empty binaryFilename.
                // These entries represent log files generated by the Cartesi machine API, e.g: log_uarch_reset
                continue;
            }

            console.log("Testing %s ...", catalog[i].binaryFilename);
            AccessLogs.Context memory a = newAccessLogsContext();

            // load ramAccessLogs
            loadBin(
                a.buffer,
                string.concat(BINARIES_PATH, catalog[i].binaryFilename)
            );
            // init pc to ram start
            EmulatorCompat.writePc(a, EmulatorConstants.UARCH_RAM_START_ADDRESS);
            // init cycle to 0
            EmulatorCompat.writeCycle(a, 0);

            UArchInterpret.interpret(a);

            uint64 x = EmulatorCompat.readX(a, TEST_STATUS_X);
            assertEq(
                // read test result from the register
                x,
                uint64(TEST_SUCCEEDED)
            );

            bool halt = EmulatorCompat.readHalt(a) != 0;
            assertTrue(halt, "machine should halt");

            uint64 cycle = EmulatorCompat.readCycle(a);
            assertEq(catalog[i].steps, cycle, "cycle values should match");
        }
    }

    function testStepEarlyReturn() public pure {
        AccessLogs.Context memory a = newAccessLogsContext();

        // init pc to ram start
        EmulatorCompat.writePc(a, EmulatorConstants.UARCH_RAM_START_ADDRESS);
        // init cycle to the final allowed uarch cycle
        EmulatorCompat.writeCycle(a, EmulatorConstants.UARCH_CYCLE_MAX);

        UArchStep.UArchStepStatus status = UArchInterpret.interpret(a);

        assertTrue(
            status == UArchStep.UArchStepStatus.UArchCycleOverflow,
            "machine should be cycle overflow"
        );

        uint64 cycle = EmulatorCompat.readCycle(a);
        assertEq(
            cycle,
            EmulatorConstants.UARCH_CYCLE_MAX,
            "step should not advance when cycle is at its maximum"
        );
        assertEq(EmulatorCompat.readHalt(a), 0, "overflow should preserve halt");

        // reset cycle to 0
        EmulatorCompat.writeCycle(a, 0);
        // set machine to halt
        EmulatorCompat.writeHalt(a, 1);

        status = UArchInterpret.interpret(a);

        assertTrue(
            status == UArchStep.UArchStepStatus.UArchHalted,
            "machine should halt"
        );

        // overflow takes precedence over halt
        EmulatorCompat.writeCycle(a, EmulatorConstants.UARCH_CYCLE_MAX);

        status = UArchInterpret.interpret(a);

        assertTrue(
            status == UArchStep.UArchStepStatus.UArchCycleOverflow,
            "machine should be cycle overflow"
        );
        assertEq(EmulatorCompat.readHalt(a), 1, "overflow should preserve halt");
    }

    function testIllegalInstruction() public {
        AccessLogs.Context memory a = newAccessLogsContext();

        // init pc to ram start
        EmulatorCompat.writePc(a, EmulatorConstants.UARCH_RAM_START_ADDRESS);
        // init cycle to 0
        EmulatorCompat.writeCycle(a, 0);

        vm.expectRevert("illegal instruction");
        ExternalUArchInterpret.interpret(a);
    }

    function testHaltEcallReachesCycleLimit() public pure {
        AccessLogs.Context memory a = newAccessLogsContext();
        a.buffer.data = bytes.concat(a.buffer.data, new bytes(8));

        EmulatorCompat.writePc(a, EmulatorConstants.UARCH_RAM_START_ADDRESS);
        EmulatorCompat.writeWord(
            a, EmulatorConstants.UARCH_RAM_START_ADDRESS, 0x73
        );
        EmulatorCompat.writeX(a, 17, EmulatorConstants.UARCH_ECALL_FN_HALT);
        EmulatorCompat.writeCycle(a, EmulatorConstants.UARCH_CYCLE_MAX - 1);

        UArchStep.UArchStepStatus status = UArchStep.step(a);

        assertTrue(
            status == UArchStep.UArchStepStatus.UArchCycleOverflow,
            "cycle overflow should take precedence over halt"
        );
        assertEq(
            EmulatorCompat.readCycle(a),
            EmulatorConstants.UARCH_CYCLE_MAX,
            "step should reach the cycle limit"
        );
        assertTrue(
            EmulatorCompat.readHalt(a) != 0,
            "halt ECALL should set a non-zero halt value"
        );
    }

    function testRemovedMarkDirtyPageEcall() public {
        // function code 3 was the mark_dirty_page ecall and has been removed, so the
        // binary that issues it must now revert as an unsupported ecall
        AccessLogs.Context memory a = newAccessLogsContext();

        loadBin(
            a.buffer,
            string.concat(
                BINARIES_PATH, "rv64ui-uarch-ecall-removed-mark-page-dirty.bin"
            )
        );

        // init pc to ram start
        EmulatorCompat.writePc(a, EmulatorConstants.UARCH_RAM_START_ADDRESS);
        // init cycle to 0
        EmulatorCompat.writeCycle(a, 0);

        vm.expectRevert("unsupported ecall function");
        ExternalUArchInterpret.interpret(a);
    }

    function loadBin(Buffer.Context memory buffer, string memory path)
        private
        view
    {
        bytes memory bytesData = vm.readFileBinary(path);
        buffer.data = bytes.concat(buffer.data, bytesData);
    }

    function loadCatalog(string memory path)
        private
        view
        returns (Entry[] memory)
    {
        string memory json = vm.readFile(path);
        bytes memory raw =
            vm.parseJsonTypeArray(json, ".", ENTRY_TYPE_DESCRIPTION);
        Entry[] memory catalog = abi.decode(raw, (Entry[]));

        return catalog;
    }

    function newAccessLogsContext()
        private
        pure
        returns (AccessLogs.Context memory)
    {
        /*
        Memory layout:
            - shadow TLB   (AR_SHADOW_TLB_LENGTH bytes)
            - shadow UArch (UARCH_SHADOW_LENGTH bytes)
            - uarch RAM   (rest of the bytes - test binary loaded here)
        */
        return AccessLogs.Context(
            bytes32(0),
            Buffer.Context(
                new bytes(
                    EmulatorConstants.AR_SHADOW_TLB_LENGTH
                        + EmulatorConstants.UARCH_SHADOW_LENGTH
                ),
                0
            )
        );
    }
}
