FROM node:12-alpine

ENV BASE /opt/cartesi
WORKDIR $BASE

RUN apk add --no-cache \
    build-base \
    git \
    openssl \
    python3 \
    python3-dev \
    py3-pip

COPY ./package.json .
COPY ./tsconfig.json .
COPY ./hardhat.config.ts .

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin
USER node

RUN npm install -g ganache-cli

USER root
COPY ./yarn.lock .
RUN yarn install

COPY ./requirements.txt .
RUN pip3 install -r requirements.txt

COPY ./contracts ./contracts
COPY ./deploy ./deploy
COPY ./deploy_step_tests.sh .

WORKDIR $BASE/test
COPY ./test/test_single_step ./test_single_step
COPY ./test/test_multiple_step ./test_multiple_step
COPY ./test/run_step_test.sh .
COPY ./test/test_step.py .

ENTRYPOINT ["/opt/cartesi/test/run_step_test.sh"]
CMD ["/opt/cartesi/test/test_single_step/tests"]
